# Generated by Django 3.1.4 on 2020-12-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repas',
            name='id_cmd',
        ),
        migrations.RemoveField(
            model_name='repas',
            name='id_plat',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='List_plat',
        ),
        migrations.DeleteModel(
            name='Repas',
        ),
    ]
